### ISSUE TITLE
Release v1.6.3-up.1

### ISSUE THREAD

**Issue by hasheddan** [upbound/universal-crossplane#232]
### What problem are you facing?

Release UXP `v1.6.3-up.1`.

### How could Upbound help solve your problem?

Release by following https://github.com/upbound/universal-crossplane/blob/main/CONTRIBUTING.md#release-process

- [x] Release UXP v1.6.3-up.1
- [x] Publish to [OLM](https://github.com/upbound/universal-crossplane/blob/main/CONTRIBUTING.md#operator-lifecycle-manager) 
- [ ] Publish to [AWS Marketplace](https://github.com/upbound/universal-crossplane/blob/main/CONTRIBUTING.md#aws-marketplace)
- [x] Publish to [Rancher Marketplace](https://github.com/upbound/universal-crossplane/blob/main/CONTRIBUTING.md#rancher-marketplace)

**Comment by hasheddan** [comment]
Release: https://github.com/upbound/universal-crossplane/releases/tag/v1.6.3-up.1

**Comment by hasheddan** [comment]
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/863
https://github.com/k8s-operatorhub/community-operators/pull/817

**Comment by hasheddan** [comment]
https://github.com/rancher/partner-charts/pull/355
