### ISSUE TITLE
 Release UXP v1.7.0-up.1

### ISSUE THREAD

**Issue by turkenh** [upbound/universal-crossplane#239]
### What problem are you facing?

Release UXP `v1.7.0-up.1`.

### How could Upbound help solve your problem?

Release by following https://github.com/upbound/universal-crossplane/blob/main/CONTRIBUTING.md#release-process

- [ ] Release UXP v1.7.0-up.1
- [ ] Publish to [OLM](https://github.com/upbound/universal-crossplane/blob/main/CONTRIBUTING.md#operator-lifecycle-manager) 
- [ ] Publish to [AWS Marketplace](https://github.com/upbound/universal-crossplane/blob/main/CONTRIBUTING.md#aws-marketplace)
- [ ] Publish to [Rancher Marketplace](https://github.com/upbound/universal-crossplane/blob/main/CONTRIBUTING.md#rancher-marketplace)

**Comment by negz** [comment]
I see this release exists so I'm going to assume this was done.
